export const AUTH_REGISTRATION_REQUESTED = "AUTH_REGISTRATION_REQUESTED";
export const AUTH_REGISTRATION_FAILED = "AUTH_REGISTRATION_FAILED";
export const AUTH_REGISTRATION_SUCCESS = "AUTH_REGISTRATION_SUCCESS";

export const AUTH_LOGIN_REQUESTED = "AUTH_LOGIN_REQUESTED";
export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_PASSWORD_UPDATE_REQUESTED = "AUTH_PASSWORD_UPDATE_REQUESTED";
export const AUTH_PASSWORD_UPDATE_FAILED = "AUTH_PASSWORD_UPDATE_FAILED";
export const AUTH_PASSWORD_UPDATE_SUCCESS = "AUTH_PASSWORD_UPDATE_SUCCESS";

export const RESET_AUTH = "RESET_AUTH";

export const USERS_REQUESTED = "USERS_REQUESTED";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAILED = "USERS_FAILED";

export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const DELETE_USER_REQUESTED = "DELETE_USER_REQUESTED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const EDIT_USER_REQUESTED = "EDIT_USER_REQUESTED";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const UPDATE_USERS_DATA = "UPDATE_USERS_DATA";

export const RESET_USERS = "RESET_USERS";

export const STATUS_FAILED = "STATUS_FAILED";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
